### ISSUE TITLE
core: Provide a way to pass filter to methods in PagerDataSource as an input parameter.

### ISSUE THREAD

**Issue by navinyashende** [lkrzyzanek/graphql-pagination#102]
PagerDataSource interface in core package provides methods like totalCount, after, etc. One of the default input parameters for these methods is args which can be either of type ArgsForward/ArgsBackward. The current args parameter does not pass the request filters down to datasource.
Ex. If I have a book datasource, where I want to fetch the total count of books written by a particular author, then I do not have a way to pass the authorName as filter for methods like totalCount. This might lead to returning the total count of books instead of books written by that author.

Expected: I should be able to provide the filter object that can be utilized to filter data from datasource based on the filter.

**Comment by lkrzyzanek** [comment]
Then you can create the pager in way like this:
```
import { dataSourcePager } from "@graphql-pagination/core";
import { Product, ProductSearchFilter, ProductSearchSource, QueryProducts_SearchArgs } from "../__generated__/resolvers-types";

export const productsPager = dataSourcePager<Product, string, QueryProducts_SearchArgs>({
    typeName: "Product",
    fetchTotalCountInResolver: true,
    typeDefDirectives: {
        edge: "@cacheControl(inheritMaxAge: true)",
        pageInfo: "@cacheControl(inheritMaxAge: true) @shareable",
        connection: "@cacheControl(inheritMaxAge: true)",
    },
});
```
