### ISSUE TITLE
Pagination issue: Passing -1 in the first field returns all records except validation error

### ISSUE THREAD

**Issue by AbhishekJRedhat** [lkrzyzanek/graphql-pagination#123]
This issue bypasses the any limit set for the pagination.

**Comment by lkrzyzanek** [comment]
I can reproduce this issue in example-mongodb so it's related only to mongodb datasource

**Comment by lkrzyzanek** [comment]
Given that spec says that first is `first takes a non-negative integer.` it makes sense to add a validation on `first` resp. `last` fields.
https://relay.dev/graphql/connections.htm#sel-FAJFFBDAAACBe-0O

**Comment by lkrzyzanek** [comment]
fixed in @graphql-pagination/mongodb 1.1.2
