### ISSUE TITLE
Pagination issue: Passing 0 or negative  in the page field returns all records present on first page

### ISSUE THREAD

**Issue by MahimaMalhotra** [lkrzyzanek/graphql-pagination#153]
Expected: Error message for validation should be thrown
![Screenshot from 2024-04-17 15-56-58](https://github.com/lkrzyzanek/graphql-pagination/assets/167301769/c41d45aa-bc75-4521-bcf7-18c96b538c7d)

**Comment by lkrzyzanek** [comment]
Expected behaviour is to throw exception similar to the argument `first`: https://github.com/lkrzyzanek/graphql-pagination/blob/main/packages/core/src/DataSourcePager.ts#L82
