### ISSUE TITLE
Pagination issue: Incorrect validation message is thrown when first argument is non-negative number

### ISSUE THREAD

**Issue by nzadapredhat** [lkrzyzanek/graphql-pagination#168]
Expected: The validation message should display "First argument" instead of "Last argument."

![Selection_120](https://github.com/user-attachments/assets/4dce2f55-0886-4777-8b9b-b87889aeed31)

**Comment by ajinkya359** [comment]
It is not a bug for this library, by default we are using the backward resolver for getting the publicDate in descending order. Thats why it is listing the "last argument" in the error message.
